version: '2'
services:
  php-nginx-fine:
    image: 192.168.11.249:80/test/php-nginx:v1.1
    container_name: php-nginx-fine1
    stdin_open: true
    tty: true
    links:
    - mysql-fine
    depends_on:
    - mysql-fine
    restart: always
  mysql-fine:
    image: 192.168.11.249:80/test/mysql_fine:v1.1
    container_name: mysql-fine1
    stdin_open: true
    tty: true
    ports:
    - "${mysql_port}:3306"
    restart: always
    environment: 
    - MYSQL_ROOT_PASSWORD=${mysql_root_password}
    
  php-lb:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
      - ${public_port}:${public_port}
  
